export const data = {
  jobs: [
    {
      id: 1,
      title: "Staff Product Engineer",
      company: "New LawnStarter",
      country: "São Paulo, Brazil",
      featured: true,
      salary: 50000,
      remote: true,
      skills: ["react", "nodejs"],
      jobType: "Fulltime",
      isNew: true,
      logo: "🏢",
      logoBg: "from-blue-500 to-purple-500",
      createdAt: "2025-05-10",
    },
    {
      id: 2,
      title: "Senior Frontend Developer",
      company: "TechCorp",
      country: "Remote (Global)",
      featured: false,
      remote: true,
      salary: 10000,
      skills: ["wordpress", "php"],
      jobType: "Fulltime",
      isNew: true,
      logo: "💻",
      logoBg: "from-green-500 to-teal-500",
      createdAt: "2025-05-18",
    },
    {
      id: 3,
      title: "UX/UI Designer",
      company: "DesignStudio",
      country: "New York, USA",
      featured: true,
      remote: false,
      skills: ["php", "laravel"],
      jobType: "Contract",
      isNew: false,
      logo: "🎨",
      logoBg: "from-pink-500 to-rose-500",
      createdAt: "2025-04-02",
    },
    {
      id: 4,
      title: "DevOps Engineer",
      company: "CloudSystems",
      country: "London, UK",
      featured: false,
      remote: true,
      salary: 80000,
      jobType: "Fulltime",
      skills: ["remix", "astro"],
      isNew: false,
      logo: "☁️",
      logoBg: "from-indigo-500 to-blue-500",
      createdAt: "2025-05-20",
    },
    {
      id: 5,
      title: "Product Manager",
      company: "InnovateLabs",
      country: "Berlin, Germany",
      featured: true,
      remote: false,
      salary: 90000,
      jobType: "remote",
      skills: ["nestjs", "nodejs"],
      isNew: true,
      logo: "📱",
      logoBg: "from-orange-500 to-red-500",
      createdAt: "2025-03-15",
    },
    {
      id: 6,
      title: "Backend Developer",
      company: "DataFlow",
      country: "Remote (EMEA)",
      featured: false,
      salary: 40000,
      remote: true,
      skills: ["react", "nextjs"],
      jobType: "Part-time",
      isNew: false,
      logo: "⚙️",
      logoBg: "from-cyan-500 to-blue-500",
      createdAt: "2025-05-22",
    },
    {
      id: 7,
      title: "Staff Product Engineer",
      company: "New LawnStarter",
      country: "São Paulo, Brazil",
      featured: true,
      salary: 20000,
      skills: ["figma", "photoshop"],
      remote: true,
      jobType: "Fulltime",
      isNew: true,
      logo: "🏢",
      logoBg: "from-blue-500 to-purple-500",
      createdAt: "2025-04-28",
    },
    {
      id: 8,
      title: "Senior Frontend Developer",
      company: "TechCorp",
      country: "Remote (Global)",
      featured: false,
      salary: 15000,
      remote: true,
      jobType: "Fulltime",
      skills: ["html", "css"],
      isNew: true,
      logo: "💻",
      logoBg: "from-green-500 to-teal-500",
      createdAt: "2025-05-01",
    },
    {
      id: 9,
      title: "UX/UI Designer",
      company: "DesignStudio",
      country: "New York, USA",
      featured: true,
      remote: false,
      salary: 25000,
      skills: ["sqllite", "reactnative"],
      jobType: "Contract",
      isNew: false,
      logo: "🎨",
      logoBg: "from-pink-500 to-rose-500",
      createdAt: "2025-02-14",
    },
    {
      id: 10,
      title: "DevOps Engineer",
      company: "CloudSystems",
      country: "London, UK",
      skills: ["fastapi", "langchain"],
      featured: false,
      remote: true,
      salary: 45000,
      jobType: "Fulltime",
      isNew: false,
      logo: "☁️",
      logoBg: "from-indigo-500 to-blue-500",
      createdAt: "2025-05-19",
    },
    {
      id: 11,
      title: "Product Manager",
      company: "InnovateLabs",
      country: "Berlin, Germany",
      skills: ["mongodb", "sql"],
      featured: true,
      salary: 30000,
      remote: false,
      jobType: "Fulltime",
      isNew: true,
      logo: "📱",
      logoBg: "from-orange-500 to-red-500",
      createdAt: "2025-05-23",
    },
    {
      id: 12,
      title: "Backend Developer",
      company: "DataFlow",
      country: "Remote (EMEA)",
      featured: false,
      salary: 100000,
      jobType: "Part time",
      isNew: false,
      skills: ["c++", "nextjs"],
      logo: "⚙️",
      logoBg: "from-cyan-500 to-blue-500",
      createdAt: "2025-01-30",
    },
  ],
};
