export const data={
      jobs : [
    {
      id: 1,
      title: "Staff Product Engineer",
      company: "New LawnStarter",
      location: "São Paulo, Brazil",
      featured: true,
      remote: true,
      jobType: "Fulltime",
      isNew: true,
      logo: "🏢",
      logoBg: "from-blue-500 to-purple-500",
    },
    {
      id: 2,
      title: "Senior Frontend Developer",
      company: "TechCorp",
      location: "Remote (Global)",
      featured: false,
      remote: true,
      jobType: "Fulltime",
      isNew: true,
      logo: "💻",
      logoBg: "from-green-500 to-teal-500",
    },
    {
      id: 3,
      title: "UX/UI Designer",
      company: "DesignStudio",
      location: "New York, USA",
      featured: true,
      remote: false,
      jobType: "Contract",
      isNew: false,
      logo: "🎨",
      logoBg: "from-pink-500 to-rose-500",
    },
    {
      id: 4,
      title: "DevOps Engineer",
      company: "CloudSystems",
      location: "London, UK",
      featured: false,
      remote: true,
      jobType: "Fulltime",
      isNew: false,
      logo: "☁️",
      logoBg: "from-indigo-500 to-blue-500",
    },
    {
      id: 5,
      title: "Product Manager",
      company: "InnovateLabs",
      location: "Berlin, Germany",
      featured: true,
      remote: false,
      jobType: "Fulltime",
      isNew: true,
      logo: "📱",
      logoBg: "from-orange-500 to-red-500",
    },
    {
      id: 6,
      title: "Backend Developer",
      company: "DataFlow",
      location: "Remote (EMEA)",
      featured: false,
      remote: true,
      jobType: "Part-time",
      isNew: false,
      logo: "⚙️",
      logoBg: "from-cyan-500 to-blue-500",
    },
    {
      id: 7,
      title: "Staff Product Engineer",
      company: "New LawnStarter",
      location: "São Paulo, Brazil",
      featured: true,
      remote: true,
      jobType: "Fulltime",
      isNew: true,
      logo: "🏢",
      logoBg: "from-blue-500 to-purple-500",
    },
    {
      id: 8,
      title: "Senior Frontend Developer",
      company: "TechCorp",
      location: "Remote (Global)",
      featured: false,
      remote: true,
      jobType: "Fulltime",
      isNew: true,
      logo: "💻",
      logoBg: "from-green-500 to-teal-500",
    },
    {
      id: 9,
      title: "UX/UI Designer",
      company: "DesignStudio",
      location: "New York, USA",
      featured: true,
      remote: false,
      jobType: "Contract",
      isNew: false,
      logo: "🎨",
      logoBg: "from-pink-500 to-rose-500",
    },
    {
      id: 10,
      title: "DevOps Engineer",
      company: "CloudSystems",
      location: "London, UK",
      featured: false,
      remote: true,
      jobType: "Fulltime",
      isNew: false,
      logo: "☁️",
      logoBg: "from-indigo-500 to-blue-500",
    },
    {
      id: 11,
      title: "Product Manager",
      company: "InnovateLabs",
      location: "Berlin, Germany",
      featured: true,
      remote: false,
      jobType: "Fulltime",
      isNew: true,
      logo: "📱",
      logoBg: "from-orange-500 to-red-500",
    },
    {
      id: 12,
      title: "Backend Developer",
      company: "DataFlow",
      location: "Remote (EMEA)",
      featured: false,
      remote: true,
      jobType: "Part-time",
      isNew: false,
      logo: "⚙️",
      logoBg: "from-cyan-500 to-blue-500",
    },
  ]
}